# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  kogs_config = debug
  kogs_cli_config = debug
endif
ifeq ($(config),release)
  kogs_config = release
  kogs_cli_config = release
endif

PROJECTS := kogs kogs-cli

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

kogs:
ifneq (,$(kogs_config))
	@echo "==== Building kogs ($(kogs_config)) ===="
	@${MAKE} --no-print-directory -C . -f kogs.make config=$(kogs_config)
endif

kogs-cli: kogs
ifneq (,$(kogs_cli_config))
	@echo "==== Building kogs-cli ($(kogs_cli_config)) ===="
	@${MAKE} --no-print-directory -C . -f kogs-cli.make config=$(kogs_cli_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f kogs.make clean
	@${MAKE} --no-print-directory -C . -f kogs-cli.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   kogs"
	@echo "   kogs-cli"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"